Added keypad to native android UI
cybex-dev/twilio_voice pull request #127
Opened 2023-05-26 20:13 UTC by tanmoy27112000

2023-05-26 20:15 UTC, tanmoy27112000 commented
@diegogarciar Hi I am new to native android development. any suggestion on reducing repetitive code will help

2023-05-27 14:02 UTC, cybex-dev requested changes
Please address the required changes, concerns or compatibility issues resolved.

Also, please update `readme` with sample of new keypad feature (many thanks for this addition) so new/existing users could have a good idea of what the new layout/ui will look like.

2023-05-27 14:02 UTC, cybex-dev commented on android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java
> +                TextView btn8 = keypadBottomSheetDialog.findViewById(R.id.NUMBER_8);
`btn8` is missing an event handler

2023-05-27 14:02 UTC, cybex-dev commented on android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java
> +                btn0.setOnClickListener(new View.OnClickListener() {
lets throw in a function like:

```btnX.setOnClickListener(() -> onNumpadAction("X"))```

2023-05-27 14:02 UTC, cybex-dev commented on android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java
> +                TextView btn0 = keypadBottomSheetDialog.findViewById(R.id.NUMBER_0);
We should check for buttons not found, linter is complaining with warning:
> Method invocation 'setOnClickListener' may produce 'NullPointerException'

2023-05-27 14:02 UTC, cybex-dev commented on android/build.gradle
> +        minSdkVersion 21
Is this required by the ```com.google.android.material:material``` library?

2023-05-27 14:02 UTC, cybex-dev commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
Good catch, could you please update do the same as in `example/android/gradle/gradle-wrapper.properties`.

i.e. `gradle-7.6.1-all.zip`

2023-05-27 14:02 UTC, cybex-dev commented on android/gradlew
@diegogarciar yay or nay on `gradlew` and `gradlew.bat`? Usually one would have this installed/configured on the dev machine no?

2023-05-27 14:02 UTC, cybex-dev commented on example/ios/Flutter/AppFrameworkInfo.plist
> +  <string>11.0</string>
Any reason for the required `MinimumOSVersion` change here and in `example/ios/PodFile`?

2023-05-27 14:02 UTC, cybex-dev commented on example/lib/main.dart
> +    WidgetsBinding.instance.removeObserver(this);
Let's keep this for now, since `pubspec.yaml` allows >= 2.14, and removing this will cause a null warning.

Incompatible with `2.14`.

2023-05-27 14:02 UTC, cybex-dev commented on example/lib/main.dart
> +    WidgetsBinding.instance.addObserver(this);
Incompatible with `2.14`.

2023-05-27 14:02 UTC, cybex-dev commented on example/lib/main.dart
> +        .push(MaterialPageRoute(fullscreenDialog: true, builder: (context) => CallScreen()));
Let's reduce unnecessary changes, that which default linter doesn't suggest/require.

2023-05-27 19:16 UTC, tanmoy27112000 commented on android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java
> +                TextView btn8 = keypadBottomSheetDialog.findViewById(R.id.NUMBER_8);
added

2023-05-27 19:25 UTC, tanmoy27112000 commented on android/src/main/java/com/twilio/twilio_voice/BackgroundCallJavaActivity.java
> +                btn0.setOnClickListener(new View.OnClickListener() {
added

2023-05-27 19:26 UTC, tanmoy27112000 commented on android/build.gradle
> +        minSdkVersion 21
it was suggested by android studio

2023-05-27 19:27 UTC, tanmoy27112000 commented on example/ios/Flutter/AppFrameworkInfo.plist
> +  <string>11.0</string>
reverted back

2023-05-27 19:48 UTC, cybex-dev commented on android/build.gradle
> +        minSdkVersion 21
Let's keep things to include as many devices/platforms as possible since change min sdk is a breaking change for existing apps.

2023-05-29 18:28 UTC, diegogarciar commented on android/gradlew
I think so too! I don't think we need to add them

2023-05-29 18:29 UTC, diegogarciar commented
Please fill in the PR info to describe motivation and what changes were done

2023-06-27 11:31 UTC, closed without merging