FIX : IOS registration not work after an unregistration , Ios caller number display added only if the client is not registered and a default name is not provided
cybex-dev/twilio_voice pull request #246
Opened 2024-07-17 13:46 UTC by bazl-E

feat: Preserve device token for VoIP push notifications
    
    Preserve the device token for VoIP push notifications to avoid the need for users to restart the app to obtain a new device 
    token. Removing the device token from UserDefaults caused registration failures.
    
    fix: IOS not displaying the caller number
    
    if the user doesn't set a default caller name it will display the incoming caller number,
    if the already set a value, the user 
    has to call 
   `await TwilioVoice.instance.setDefaultCallerName('');` 
    to make this work

2025-03-28 16:28 UTC, AndreiMisiukevich commented
This looks like a pretty important fix, doesn't it?

2025-06-16 10:01 UTC, cybex-dev requested changes
Many thanks for your contributions!

2025-06-16 10:01 UTC, cybex-dev commented on android/src/main/kotlin/com/twilio/twilio_voice/types/TelecomManagerExtension.kt
> +        if (Build.MANUFACTURER.equals("Samsung", ignoreCase = true)|| Build.MANUFACTURER.equals("OnePlus", ignoreCase = true)) {
Awesome, thank you - I do not own a OnePlus but hopefully it works as expected

2025-06-16 10:01 UTC, cybex-dev commented on android/build.gradle
> +    implementation("com.twilio:voice-android:6.6.4")
Feel free to update to latest to-date

2025-06-16 10:01 UTC, cybex-dev commented on ios/twilio_voice.podspec
> +  s.dependency 'TwilioVoice','~> 6.11.3'
Feel free to update to latest to-date

2025-06-16 10:01 UTC, cybex-dev commented on ios/Classes/SwiftTwilioVoicePlugin.swift
> +        callUpdate.localizedCallerName = formatUSPhoneNumber(from)
Great idea - I've got an improvement of this in-progress for developers to interpret caller names directly from call parameters, client map, etc.

2025-06-16 10:01 UTC, cybex-dev commented on ios/Classes/SwiftTwilioVoicePlugin.swift
> +        // self.showMissedCallNotification(from: cancelledCallInvite.from, to: cancelledCallInvite.to)
As great as this might be to 'easify', this will break expected functionality for most other users making use of `twilio_voice`.

2025-06-16 10:01 UTC, cybex-dev commented on ios/Classes/SwiftTwilioVoicePlugin.swift
> +//        UserDefaults.standard.removeObject(forKey: kCachedDeviceToken)
Great catch, I've already merged this from another PR.

2025-06-20 15:01 UTC, closed without merging

2025-06-20 15:01 UTC, bazl-E commented
i will open a new PR with changes